### PR TITLE
Fix collision detection when using Verlet integrator method

### LINKED ISSUE #31: Switching to or from Verlet integrator method causes suddent speed burst

### PR DESCRIPTION
**Pull request by mskrip**
Close #31

### CODE REVIEW

File: physical-based-animations.go [hunk 1]
```diff
@@ -48,6 +48,12 @@ func updateParticles(
 					math.Atan2(unitNormalVector.Y, unitNormalVector.X)))
 
 			particles[i].speed = newSpeed.Scaled(coefficientOfRestitution)
+
+			if positionIntegrator == Verlet {
+				particles[i].nextPosition = newPosition.Add(particles[i].speed.Scaled(PixelsPerMeter).Scaled(dt)).Add(
```
Comment (mitas1) [inline physical-based-animations.go]: As I mentionned in previus MR, wrapping lines after 100 charaters is good habit. As you can see this line is not completely visible, I have to scroll:
screen shot 2018-01-15 at 20 55 47
What do you think about line spliting in go lang ? Is this suggestion irelevant?

Comment (mskrip) [reply physical-based-animations.go]: Github autobreaks the line for me and this math is more readable in a line of code rather then being split imo
image

**Comment by mitas1** [comment]
LGTM, but consider line wrapping, I mean for this MR it is not important, but in general the principle of wrapping lines is important.
